#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "Running cargo fmt..."
cargo fmt --all
git add -u

echo "Running cargo clippy..."
cargo clippy --all-features --all-targets -- -D warnings

echo "Pre-commit checks passed."
